spool drop_table.log;

DROP TABLE CISSSCC.S09S2_08_APINFO CASCADE CONSTRAINTS;
DROP TABLE CISSSCC.S09T2_08_APINFO_10 CASCADE CONSTRAINTS;

DROP TABLE CISSSCC.S09S2_08_APPRINFO CASCADE CONSTRAINTS;
DROP TABLE CISSSCC.S09T2_08_APPRINFO_10 CASCADE CONSTRAINTS;

DROP TABLE CISSSCC.S09S2_08_REFUSE CASCADE CONSTRAINTS;
DROP TABLE CISSSCC.S09T2_08_REFUSE_10 CASCADE CONSTRAINTS;

DROP TABLE CISSSCC.S09S2_08_SVYINFO CASCADE CONSTRAINTS;
DROP TABLE CISSSCC.S09T2_08_SVYINFO_10 CASCADE CONSTRAINTS;

DROP TABLE CISSSCC.S09S2_08_WORKFLOWINFO CASCADE CONSTRAINTS;
DROP TABLE CISSSCC.S09T2_08_WORKFLOWINFO_10 CASCADE CONSTRAINTS;

spool off;