spool h:\create_table.log;

CREATE TABLE CISSSCC.S09S2_08_APINFO
(
  RECORD_DATE    DATE                           NOT NULL,
  AUTHORG_CODE   VARCHAR2(9 BYTE),
  SALNBR         VARCHAR2(9 BYTE),
  LINE_CODE      CHAR(1 BYTE),
  PLACE_CODE     CHAR(1 BYTE),
  CARD_CODE      CHAR(5 BYTE),
  REG_DADD       NUMBER(10)                     DEFAULT 0,
  REG_MADD       NUMBER(10)                     DEFAULT 0,
  REG_YADD       NUMBER(10)                     DEFAULT 0,
  A_PASS_DADD    NUMBER(10)                     DEFAULT 0,
  A_PASS_MADD    NUMBER(10)                     DEFAULT 0,
  A_PASS_YADD    NUMBER(10)                     DEFAULT 0,
  A_REFUSE_DADD  NUMBER(10)                     DEFAULT 0,
  A_REFUSE_MADD  NUMBER(10)                     DEFAULT 0,
  A_REFUSE_YADD  NUMBER(10)                     DEFAULT 0,
  MEND_DADD      NUMBER(10)                     DEFAULT 0,
  MEND_MADD      NUMBER(10)                     DEFAULT 0,
  MEND_YADD      NUMBER(10)                     DEFAULT 0,
  MEND_END       NUMBER(10)                     DEFAULT 0,
  NOTDEAL_END    NUMBER(10)                     DEFAULT 0,
  MCARD_DADD     NUMBER(10)                     DEFAULT 0,
  MCARD_MADD     NUMBER(10)                     DEFAULT 0,
  MCARD_YADD     NUMBER(10)                     DEFAULT 0,
  DEAL_YNUM      NUMBER(10)                     DEFAULT 0,
  DEAL_YTIME     NUMBER(10)                     DEFAULT 0,
  MAX_YTIME      NUMBER(10),
  MIN_YTIME      NUMBER(10),
  ASSIGN_YNUM    NUMBER(10)                     DEFAULT 0,
  OT_YNUM        NUMBER(10)                     DEFAULT 0,
  OT_YTIME       NUMBER(10)                     DEFAULT 0
);
COMMENT ON TABLE CISSSCC.S09S2_08_APINFO IS '23  进件信息';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.RECORD_DATE IS '日期';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.AUTHORG_CODE IS '发卡机构代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.SALNBR IS '营销人员代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.LINE_CODE IS '条线代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.PLACE_CODE IS '渠道代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.CARD_CODE IS '卡种代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.REG_DADD IS '进件本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.REG_MADD IS '进件本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.REG_YADD IS '进件本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.A_PASS_DADD IS '审批通过本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.A_PASS_MADD IS '审批通过本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.A_PASS_YADD IS '审批通过本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.A_REFUSE_DADD IS '审批拒绝本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.A_REFUSE_MADD IS '审批拒绝本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.A_REFUSE_YADD IS '审批拒绝本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MEND_DADD IS '补件本日新增(时点值):1 通过2 拒绝3 未处理4. 补件';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MEND_MADD IS '补件本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MEND_YADD IS '补件本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MEND_END IS '补件量(时点值)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.NOTDEAL_END IS '未处理量(时点值)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MCARD_DADD IS '开卡本日新增  0 未开卡1 已开卡';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MCARD_MADD IS '开卡本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MCARD_YADD IS '开卡本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.DEAL_YNUM IS '处理总数';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.DEAL_YTIME IS '总耗时';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MAX_YTIME IS '最大耗时';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.MIN_YTIME IS '最小耗时';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.ASSIGN_YNUM IS '分配总量';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.OT_YNUM IS '超时总件数';
COMMENT ON COLUMN CISSSCC.S09S2_08_APINFO.OT_YTIME IS '超时总时间';



CREATE TABLE CISSSCC.S09T2_08_APINFO_10
(
  RECORD_DATE    DATE                           NOT NULL,
  AUTHORG_CODE   VARCHAR2(9 BYTE),
  SALNBR         VARCHAR2(9 BYTE),
  LINE_CODE      CHAR(1 BYTE),
  PLACE_CODE     CHAR(1 BYTE),
  CARD_CODE      CHAR(5 BYTE),
  REG_DADD       NUMBER(10),
  REG_MADD       NUMBER(10),
  REG_YADD       NUMBER(10),
  A_PASS_DADD    NUMBER(10),
  A_PASS_MADD    NUMBER(10),
  A_PASS_YADD    NUMBER(10),
  A_REFUSE_DADD  NUMBER(10),
  A_REFUSE_MADD  NUMBER(10),
  A_REFUSE_YADD  NUMBER(10),
  MEND_DADD      NUMBER(10),
  MEND_MADD      NUMBER(10),
  MEND_YADD      NUMBER(10),
  MEND_END       NUMBER(10),
  NOTDEAL_END    NUMBER(10),
  MCARD_DADD     NUMBER(10),
  MCARD_MADD     NUMBER(10),
  MCARD_YADD     NUMBER(10),
  DEAL_YNUM      NUMBER(10),
  DEAL_YTIME     NUMBER(10),
  MAX_YTIME      NUMBER(10),
  MIN_YTIME      NUMBER(10),
  ASSIGN_YNUM    NUMBER(10),
  OT_YNUM        NUMBER(10),
  OT_YTIME       NUMBER(10)
);


CREATE TABLE CISSSCC.S09S2_08_APPRINFO
(
  RECORD_DATE     DATE                          NOT NULL,
  AUTHORG_CODE    VARCHAR2(9 BYTE),
  SALNBR          VARCHAR2(9 BYTE),
  LINE_CODE       CHAR(1 BYTE),
  PLACE_CODE      CHAR(1 BYTE),
  CARD_CODE       CHAR(5 BYTE),
  EXPAPPR_STATE   CHAR(1 BYTE),
  OPERORG_CODE    VARCHAR2(9 BYTE),
  OPER_CODE       VARCHAR2(11 BYTE),
  STEP_DEXIST     NUMBER(10)                    DEFAULT 0,
  STEP_DADD       NUMBER(10)                    DEFAULT 0,
  STEP_MADD       NUMBER(10)                    DEFAULT 0,
  STEP_YADD       NUMBER(10)                    DEFAULT 0,
  PASS_DADD       NUMBER(10)                    DEFAULT 0,
  PASS_MADD       NUMBER(10)                    DEFAULT 0,
  PASS_YADD       NUMBER(10)                    DEFAULT 0,
  REFUSE_DADD     NUMBER(10)                    DEFAULT 0,
  REFUSE_MADD     NUMBER(10)                    DEFAULT 0,
  REFUSE_YADD     NUMBER(10)                    DEFAULT 0,
  MEND_DADD       NUMBER(10)                    DEFAULT 0,
  MEND_MADD       NUMBER(10)                    DEFAULT 0,
  MEND_YADD       NUMBER(10)                    DEFAULT 0,
  DSUGCREDIT      NUMBER(16)                    DEFAULT 0,
  MSUGCREDIT      NUMBER(16)                    DEFAULT 0,
  YSUGCREDIT      NUMBER(16)                    DEFAULT 0,
  MAX_DCR         NUMBER(10),
  MIN_DCR         NUMBER(10),
  MAX_MCR         NUMBER(10),
  MIN_MCR         NUMBER(10),
  MAX_YCR         NUMBER(10),
  MIN_YCR         NUMBER(10),
  CREDIT_RANGE1   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE2   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE3   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE4   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE5   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE6   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE7   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE8   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE9   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE10  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE11  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE12  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE13  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE14  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE15  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE16  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE17  NUMBER(10)                    DEFAULT 0
);
COMMENT ON TABLE CISSSCC.S09S2_08_APPRINFO IS '23  审批环节信息';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.RECORD_DATE IS '日期';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.AUTHORG_CODE IS '发卡机构代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.SALNBR IS '营销人员代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.LINE_CODE IS '条线代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.PLACE_CODE IS '渠道代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CARD_CODE IS '卡种代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.EXPAPPR_STATE IS '例外审批状态  1 例外审批0 其他情况';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.OPERORG_CODE IS '操作机构代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.OPER_CODE IS '操作员代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.STEP_DEXIST IS '本日存量';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.STEP_DADD IS '本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.STEP_MADD IS '本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.STEP_YADD IS '本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.PASS_DADD IS '通过本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.PASS_MADD IS '通过本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.PASS_YADD IS '通过本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.REFUSE_DADD IS '拒绝本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.REFUSE_MADD IS '拒绝本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.REFUSE_YADD IS '拒绝本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MEND_DADD IS '补件本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MEND_MADD IS '补件本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MEND_YADD IS '补件本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.DSUGCREDIT IS '本日建议额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MSUGCREDIT IS '本月建议额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.YSUGCREDIT IS '本年建议额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MAX_DCR IS '本日最高额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MIN_DCR IS '本日最低额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MAX_MCR IS '本月最高额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MIN_MCR IS '本月最低额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MAX_YCR IS '本年最高额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.MIN_YCR IS '本年最低额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE1 IS '额度区间1(0~1千)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE2 IS '额度区间2(1千~5千)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE3 IS '额度区间3(5千~1万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE4 IS '额度区间4(1万~3万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE5 IS '额度区间5(3万~5万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE6 IS '额度区间6(5万~8万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE7 IS '额度区间7(8万~10万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE8 IS '额度区间8(10万~15万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE9 IS '额度区间9(15万~20万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE10 IS '额度区间10(20万~25万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE11 IS '额度区间11(25万~30万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE12 IS '额度区间12(30万~50万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE13 IS '额度区间13(50万~80万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE14 IS '额度区间14(80万~100万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE15 IS '额度区间15(100万~200万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE16 IS '额度区间16(200万~300万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_APPRINFO.CREDIT_RANGE17 IS '额度区间17(300万以上)';


CREATE TABLE CISSSCC.S09T2_08_APPRINFO_10
(
  RECORD_DATE     DATE                          NOT NULL,
  AUTHORG_CODE    VARCHAR2(9 BYTE),
  SALNBR          VARCHAR2(9 BYTE),
  LINE_CODE       CHAR(1 BYTE),
  PLACE_CODE      CHAR(1 BYTE),
  CARD_CODE       CHAR(5 BYTE),
  EXPAPPR_STATE   CHAR(1 BYTE),
  OPERORG_CODE    VARCHAR2(9 BYTE),
  OPER_CODE       VARCHAR2(11 BYTE),
  STEP_DEXIST     NUMBER(10),
  STEP_DADD       NUMBER(10),
  STEP_MADD       NUMBER(10),
  STEP_YADD       NUMBER(10),
  PASS_DADD       NUMBER(10),
  PASS_MADD       NUMBER(10),
  PASS_YADD       NUMBER(10),
  REFUSE_DADD     NUMBER(10),
  REFUSE_MADD     NUMBER(10),
  REFUSE_YADD     NUMBER(10),
  MEND_DADD       NUMBER(10),
  MEND_MADD       NUMBER(10),
  MEND_YADD       NUMBER(10),
  DSUGCREDIT      NUMBER(16),
  MSUGCREDIT      NUMBER(16),
  YSUGCREDIT      NUMBER(16),
  MAX_DCR         NUMBER(10),
  MIN_DCR         NUMBER(10),
  MAX_MCR         NUMBER(10),
  MIN_MCR         NUMBER(10),
  MAX_YCR         NUMBER(10),
  MIN_YCR         NUMBER(10),
  CREDIT_RANGE1   NUMBER(10),
  CREDIT_RANGE2   NUMBER(10),
  CREDIT_RANGE3   NUMBER(10),
  CREDIT_RANGE4   NUMBER(10),
  CREDIT_RANGE5   NUMBER(10),
  CREDIT_RANGE6   NUMBER(10),
  CREDIT_RANGE7   NUMBER(10),
  CREDIT_RANGE8   NUMBER(10),
  CREDIT_RANGE9   NUMBER(10),
  CREDIT_RANGE10  NUMBER(10),
  CREDIT_RANGE11  NUMBER(10),
  CREDIT_RANGE12  NUMBER(10),
  CREDIT_RANGE13  NUMBER(10),
  CREDIT_RANGE14  NUMBER(10),
  CREDIT_RANGE15  NUMBER(10),
  CREDIT_RANGE16  NUMBER(10),
  CREDIT_RANGE17  NUMBER(10)
);



CREATE TABLE CISSSCC.S09S2_08_REFUSE
(
  RECORD_DATE    DATE                           NOT NULL,
  AUTHORG_CODE   VARCHAR2(9 BYTE),
  SALNBR         VARCHAR2(9 BYTE),
  STEP_CODE      NUMBER(2),
  LINE_CODE      CHAR(1 BYTE),
  PLACE_CODE     CHAR(1 BYTE),
  CARD_CODE      CHAR(5 BYTE),
  OPERORG_CODE   VARCHAR2(9 BYTE),
  OPER_CODE      VARCHAR2(11 BYTE),
  FREFUSE        VARCHAR2(30 BYTE),
  SREFUSE        VARCHAR2(30 BYTE),
  A_REFUSE_DADD  NUMBER(10)                     DEFAULT 0,
  A_REFUSE_MADD  NUMBER(10)                     DEFAULT 0,
  A_REFUSE_YADD  NUMBER(10)                     DEFAULT 0
);
COMMENT ON TABLE CISSSCC.S09S2_08_REFUSE IS '23  拒绝原因,根据环节代码来判断18  征信环节20  审批环节30  审批后不能改环节（进件报表新加）';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.RECORD_DATE IS '日期';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.AUTHORG_CODE IS '发卡机构代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.SALNBR IS '营销人员代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.STEP_CODE IS '环节代码18  征信环节20  审批环节30  审批后不能改环节（进件报表新加）';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.LINE_CODE IS '条线代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.PLACE_CODE IS '渠道代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.CARD_CODE IS '卡种代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.OPERORG_CODE IS '操作机构代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.OPER_CODE IS '操作员代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.FREFUSE IS '一级拒绝原因';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.SREFUSE IS '二级拒绝原因';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.A_REFUSE_DADD IS '拒绝本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.A_REFUSE_MADD IS '拒绝本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_REFUSE.A_REFUSE_YADD IS '拒绝本年新增';



CREATE TABLE CISSSCC.S09T2_08_REFUSE_10
(
  RECORD_DATE    DATE                           NOT NULL,
  AUTHORG_CODE   VARCHAR2(9 BYTE),
  SALNBR         VARCHAR2(9 BYTE),
  STEP_CODE      NUMBER(2),
  LINE_CODE      CHAR(1 BYTE),
  PLACE_CODE     CHAR(1 BYTE),
  CARD_CODE      CHAR(5 BYTE),
  OPERORG_CODE   VARCHAR2(9 BYTE),
  OPER_CODE      VARCHAR2(11 BYTE),
  FREFUSE        VARCHAR2(30 BYTE),
  SREFUSE        VARCHAR2(30 BYTE),
  A_REFUSE_DADD  NUMBER(10),
  A_REFUSE_MADD  NUMBER(10),
  A_REFUSE_YADD  NUMBER(10)
);



CREATE TABLE CISSSCC.S09S2_08_SVYINFO
(
  RECORD_DATE     DATE                          NOT NULL,
  AUTHORG_CODE    VARCHAR2(9 BYTE),
  SALNBR          VARCHAR2(9 BYTE),
  LINE_CODE       CHAR(1 BYTE),
  PLACE_CODE      CHAR(1 BYTE),
  CARD_CODE       CHAR(5 BYTE),
  APPTYPE         CHAR(2 BYTE),
  IS_CALL         CHAR(1 BYTE),
  OPERORG_CODE    VARCHAR2(9 BYTE),
  OPER_CODE       VARCHAR2(11 BYTE),
  STEP_DEXIST     NUMBER(10)                    DEFAULT 0,
  STEP_DADD       NUMBER(10)                    DEFAULT 0,
  STEP_MADD       NUMBER(10)                    DEFAULT 0,
  STEP_YADD       NUMBER(10)                    DEFAULT 0,
  PASS_DADD       NUMBER(10)                    DEFAULT 0,
  PASS_MADD       NUMBER(10)                    DEFAULT 0,
  PASS_YADD       NUMBER(10)                    DEFAULT 0,
  REFUSE_DADD     NUMBER(10)                    DEFAULT 0,
  REFUSE_MADD     NUMBER(10)                    DEFAULT 0,
  REFUSE_YADD     NUMBER(10)                    DEFAULT 0,
  MEND_DADD       NUMBER(10)                    DEFAULT 0,
  MEND_MADD       NUMBER(10)                    DEFAULT 0,
  MEND_YADD       NUMBER(10)                    DEFAULT 0,
  DSUGCREDIT      NUMBER(16)                    DEFAULT 0,
  CALL_STEP_DADD  NUMBER(10)                    DEFAULT 0,
  CALL_STEP_MADD  NUMBER(10)                    DEFAULT 0,
  CALL_STEP_YADD  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE1   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE2   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE3   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE4   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE5   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE6   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE7   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE8   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE9   NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE10  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE11  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE12  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE13  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE14  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE15  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE16  NUMBER(10)                    DEFAULT 0,
  CREDIT_RANGE17  NUMBER(10)                    DEFAULT 0
);

COMMENT ON TABLE CISSSCC.S09S2_08_SVYINFO IS '23  征信环节信息';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.RECORD_DATE IS '日期';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.AUTHORG_CODE IS '发卡机构代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.SALNBR IS '营销人员代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.LINE_CODE IS '条线代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.PLACE_CODE IS '渠道代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CARD_CODE IS '卡种代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.APPTYPE IS '进件类型';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.IS_CALL IS '核打情况  1 核打0 未核打';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.OPERORG_CODE IS '操作机构代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.OPER_CODE IS '操作员代码';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.STEP_DEXIST IS '本日存量';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.STEP_DADD IS '本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.STEP_MADD IS '本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.STEP_YADD IS '本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.PASS_DADD IS '通过本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.PASS_MADD IS '通过本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.PASS_YADD IS '通过本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.REFUSE_DADD IS '拒绝本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.REFUSE_MADD IS '拒绝本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.REFUSE_YADD IS '拒绝本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.MEND_DADD IS '补件本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.MEND_MADD IS '补件本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.MEND_YADD IS '补件本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.DSUGCREDIT IS '本日建议额度';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CALL_STEP_DADD IS '核打电话本日新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CALL_STEP_MADD IS '核打电话本月新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CALL_STEP_YADD IS '核打电话本年新增';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE1 IS '额度区间1(0~1千)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE2 IS '额度区间2(1千~5千)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE3 IS '额度区间3(5千~1万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE4 IS '额度区间4(1万~3万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE5 IS '额度区间5(3万~5万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE6 IS '额度区间6(5万~8万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE7 IS '额度区间7(8万~10万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE8 IS '额度区间8(10万~15万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE9 IS '额度区间9(15万~20万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE10 IS '额度区间10(20万~25万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE11 IS '额度区间11(25万~30万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE12 IS '额度区间12(30万~50万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE13 IS '额度区间13(50万~80万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE14 IS '额度区间14(80万~100万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE15 IS '额度区间15(100万~200万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE16 IS '额度区间16(200万~300万)';
COMMENT ON COLUMN CISSSCC.S09S2_08_SVYINFO.CREDIT_RANGE17 IS '额度区间17(300万以上)';




CREATE TABLE CISSSCC.S09T2_08_SVYINFO_10
(
  RECORD_DATE     DATE                          NOT NULL,
  AUTHORG_CODE    VARCHAR2(9 BYTE),
  SALNBR          VARCHAR2(9 BYTE),
  LINE_CODE       CHAR(1 BYTE),
  PLACE_CODE      CHAR(1 BYTE),
  CARD_CODE       CHAR(5 BYTE),
  APPTYPE         CHAR(2 BYTE),
  IS_CALL         CHAR(1 BYTE),
  OPERORG_CODE    VARCHAR2(9 BYTE),
  OPER_CODE       VARCHAR2(11 BYTE),
  STEP_DEXIST     NUMBER(10),
  STEP_DADD       NUMBER(10),
  STEP_MADD       NUMBER(10),
  STEP_YADD       NUMBER(10),
  PASS_DADD       NUMBER(10),
  PASS_MADD       NUMBER(10),
  PASS_YADD       NUMBER(10),
  REFUSE_DADD     NUMBER(10),
  REFUSE_MADD     NUMBER(10),
  REFUSE_YADD     NUMBER(10),
  MEND_DADD       NUMBER(10),
  MEND_MADD       NUMBER(10),
  MEND_YADD       NUMBER(10),
  DSUGCREDIT      NUMBER(16),
  CALL_STEP_DADD  NUMBER(10),
  CALL_STEP_MADD  NUMBER(10),
  CALL_STEP_YADD  NUMBER(10),
  CREDIT_RANGE1   NUMBER(10),
  CREDIT_RANGE2   NUMBER(10),
  CREDIT_RANGE3   NUMBER(10),
  CREDIT_RANGE4   NUMBER(10),
  CREDIT_RANGE5   NUMBER(10),
  CREDIT_RANGE6   NUMBER(10),
  CREDIT_RANGE7   NUMBER(10),
  CREDIT_RANGE8   NUMBER(10),
  CREDIT_RANGE9   NUMBER(10),
  CREDIT_RANGE10  NUMBER(10),
  CREDIT_RANGE11  NUMBER(10),
  CREDIT_RANGE12  NUMBER(10),
  CREDIT_RANGE13  NUMBER(10),
  CREDIT_RANGE14  NUMBER(10),
  CREDIT_RANGE15  NUMBER(10),
  CREDIT_RANGE16  NUMBER(10),
  CREDIT_RANGE17  NUMBER(10)
);




create table S09S2_08_WORKFLOWINFO
(
  RECORD_DATE     DATE not null,
  AUTHORG_CODE    VARCHAR2(9),
  SALNBR          VARCHAR2(9),
  LINE_CODE       CHAR(1),
  PLACE_CODE      CHAR(1),
  CARD_CODE       CHAR(5),
  STEP_CODE       NUMBER(2),
  OPERORG_CODE    VARCHAR2(9),
  OPER_CODE       VARCHAR2(11),
  STEP_DEXIST     NUMBER(10),
  STEP_DADD       NUMBER(10),
  STEP_MADD       NUMBER(10),
  STEP_YADD       NUMBER(10),
  REG_DADD        NUMBER(10),
  REG_MADD        NUMBER(10),
  REG_YADD        NUMBER(10),
  A_PASS_DADD     NUMBER(10),
  A_PASS_MADD     NUMBER(10),
  A_PASS_YADD     NUMBER(10),
  A_REFUSE_DADD   NUMBER(10),
  A_REFUSE_MADD   NUMBER(10),
  A_REFUSE_YADD   NUMBER(10),
  MEND_END        NUMBER(10),
  NOTDEAL_END     NUMBER(10),
  MCARD_DADD      NUMBER(10),
  MCARD_MADD      NUMBER(10),
  MCARD_YADD      NUMBER(10),
  STEP_DEAL_DADD  NUMBER(10),
  STEP_DEAL_MADD  NUMBER(10),
  STEP_DEAL_YADD  NUMBER(10),
  STEP_DEAL_DTIME NUMBER(10),
  STEP_DEAL_MTIME NUMBER(10),
  STEP_DEAL_YTIME NUMBER(10),
  MAX_DTIME       NUMBER(4),
  MAX_MTIME       NUMBER(4),
  MAX_YTIME       NUMBER(4),
  MIN_DTIME       NUMBER(4),
  MIN_MTIME       NUMBER(4),
  MIN_YTIME       NUMBER(4),
  OT_DADD         NUMBER(10),
  OT_MADD         NUMBER(10),
  OT_YADD         NUMBER(10),
  OT_DTIME        NUMBER(10),
  OT_MTIME        NUMBER(10),
  OT_YTIME        NUMBER(10)
);






CREATE TABLE CISSSCC.S09T2_08_WORKFLOWINFO_10
(
  RECORD_DATE      DATE                         NOT NULL,
  AUTHORG_CODE     VARCHAR2(9 BYTE),
  SALNBR           VARCHAR2(9 BYTE),
  LINE_CODE        CHAR(1 BYTE),
  PLACE_CODE       CHAR(1 BYTE),
  CARD_CODE        CHAR(5 BYTE),
  STEP_CODE        NUMBER(2),
  OPERORG_CODE     VARCHAR2(9 BYTE),
  OPER_CODE        VARCHAR2(11 BYTE),
  STEP_DEXIST      NUMBER(10),
  STEP_DADD        NUMBER(10),
  STEP_MADD        NUMBER(10),
  STEP_YADD        NUMBER(10),
  REG_DADD         NUMBER(10),
  REG_MADD         NUMBER(10),
  REG_YADD         NUMBER(10),
  A_PASS_DADD      NUMBER(10),
  A_PASS_MADD      NUMBER(10),
  A_PASS_YADD      NUMBER(10),
  A_REFUSE_DADD    NUMBER(10),
  A_REFUSE_MADD    NUMBER(10),
  A_REFUSE_YADD    NUMBER(10),
  MEND_END         NUMBER(10),
  NOTDEAL_END      NUMBER(10),
  MCARD_DADD       NUMBER(10),
  MCARD_MADD       NUMBER(10),
  MCARD_YADD       NUMBER(10),
  STEP_DEAL_DADD   NUMBER(10),
  STEP_DEAL_MADD   NUMBER(10),
  STEP_DEAL_YADD   NUMBER(10),
  STEP_DEAL_DTIME  NUMBER(10),
  STEP_DEAL_MTIME  NUMBER(10),
  STEP_DEAL_YTIME  NUMBER(10),
  MAX_DTIME        NUMBER(4),
  MAX_MTIME        NUMBER(4),
  MAX_YTIME        NUMBER(4),
  MIN_DTIME        NUMBER(4),
  MIN_MTIME        NUMBER(4),
  MIN_YTIME        NUMBER(4),
  OT_DADD          NUMBER(10),
  OT_MADD          NUMBER(10),
  OT_YADD          NUMBER(10),
  OT_DTIME         NUMBER(10),
  OT_MTIME         NUMBER(10),
  OT_YTIME         NUMBER(10)
);

spool off;